In [1]:
import glob
import os
import pandas as pd

In [2]:
folder_name = '/home/sai/Projects/COVID-19/csse_covid_19_data/'
file_type = 'csv'
seperator =','
#df = pd.concat([pd.read_csv(f, sep=seperator) for f in glob.glob(folder_name + "/*."+file_type)],ignore_index=True)

In [3]:
file_list = glob.glob(folder_name + "csse_covid_19_daily_reports_us" +"/*."+file_type)
df_list = []
for f in file_list:
    tmp_df = pd.read_csv(f, sep=',')
    tmp_df['date'] = os.path.splitext(os.path.basename(f))[0]
    df_list.append(tmp_df)
df = pd.concat(df_list)

In [4]:
df

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,Incident_Rate,People_Tested,People_Hospitalized,Mortality_Rate,UID,ISO3,Testing_Rate,Hospitalization_Rate,date
0,Alabama,US,2020-05-04 02:32:32,32.3182,-86.9023,7888,290,0.0,7598.0,1.0,168.227197,92500.0,1035.0,3.676471,84000001.0,USA,1972.745403,13.121197,05-03-2020
1,Alaska,US,2020-05-04 02:32:32,61.3707,-152.4044,368,9,262.0,97.0,2.0,61.564302,21578.0,NaN,2.445652,84000002.0,USA,3609.876386,NaN,05-03-2020
2,American Samoa,US,2020-05-04 02:32:32,-14.2710,-170.1320,0,0,0.0,0.0,60.0,0.000000,57.0,NaN,NaN,16.0,ASM,102.442444,NaN,05-03-2020
3,Arizona,US,2020-05-04 02:32:32,33.7298,-111.4312,8640,362,1597.0,6681.0,4.0,118.702238,81119.0,1348.0,4.189815,84000004.0,USA,1114.468388,15.601852,05-03-2020
4,Arkansas,US,2020-05-04 02:32:32,34.9697,-92.3731,3437,76,1999.0,1362.0,5.0,132.752575,52890.0,427.0,2.211231,84000005.0,USA,2042.852392,12.423625,05-03-2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53,Virginia,US,2020-07-15 04:34:53,37.7693,-78.1700,72443,1977,9423.0,61043.0,51.0,848.724020,830850.0,10550.0,2.729042,84000051.0,USA,9734.030233,14.563174,07-14-2020
54,Washington,US,2020-07-15 04:34:53,47.4009,-121.4905,42304,1404,NaN,40900.0,53.0,555.542934,708274.0,4778.0,3.318835,84000053.0,USA,9301.168119,11.294440,07-14-2020
55,West Virginia,US,2020-07-15 04:34:53,38.4912,-80.9545,4407,97,2982.0,1328.0,54.0,245.906167,214012.0,NaN,2.201044,84000054.0,USA,11941.654340,NaN,07-14-2020
56,Wisconsin,US,2020-07-15 04:34:53,44.2685,-89.6165,37906,826,29275.0,7805.0,55.0,651.033571,714544.0,3892.0,2.179075,84000055.0,USA,12272.255898,10.267504,07-14-2020
57,Wyoming,US,2020-07-15 04:34:53,42.7560,-107.3025,1950,22,1462.0,466.0,56.0,336.927806,40028.0,128.0,1.128205,84000056.0,USA,6916.177545,6.564103,07-14-2020

In [5]:
df_sorted = df.sort_values(["Province_State", "date"])

In [6]:
df_sorted["Province_State"].unique()

array(['Alabama', 'Alaska', 'American Samoa', 'Arizona', 'Arkansas',
       'California', 'Colorado', 'Connecticut', 'Delaware',
       'Diamond Princess', 'District of Columbia', 'Florida', 'Georgia',
       'Grand Princess', 'Guam', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Northern Mariana Islands', 'Ohio', 'Oklahoma',
       'Oregon', 'Pennsylvania', 'Puerto Rico', 'Recovered',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virgin Islands', 'Virginia',
       'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'],
      dtype=object)

In [7]:
df_sorted.to_csv("all.csv", index=False)

In [28]:
file_list = glob.glob(folder_name + "csse_covid_19_daily_reports" +"/*."+file_type)
df_list = []
for f in file_list:
    tmp_df = pd.read_csv(f, sep=',')
    tmp_df['date'] = os.path.splitext(os.path.basename(f))[0]
    df_list.append(tmp_df)
df_daily = pd.concat(df_list)

In [29]:
df_daily.isna().sum()

FIPS                    65261
Admin2                  64453
Province_State          29295
Country_Region           7617
Last_Update              7617
Lat                     15391
Long_                   15391
Confirmed                  19
Deaths                    441
Recovered                 388
Active                   7688
Combined_Key             7617
date                        0
Incidence_Rate         226585
Case-Fatality_Ratio    225446
Province/State         428772
Country/Region         425513
Last Update            425513
Latitude               428331
Longitude              428331
dtype: int64

In [30]:
df_daily['Province_State'] = df_daily['Province_State'].combine_first(df_daily['Province/State'])
df_daily['Country_Region'] = df_daily['Country_Region'].combine_first(df_daily['Country/Region'])
df_daily['Last_Update'] = df_daily['Last_Update'].combine_first(df_daily['Last Update'])
df_daily['Lat'] = df_daily['Lat'].combine_first(df_daily['Latitude'])
df_daily['Long_'] = df_daily['Long_'].combine_first(df_daily['Longitude'])
df_daily.drop(columns=['Province/State', 'Country/Region', 'Last Update', 'Latitude', 'Longitude'], inplace=True)

In [35]:
df_daily_sorted = df_daily.sort_values(["Country_Region", "Province_State", "Admin2"])

In [36]:
df_daily_sorted

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,date,Incidence_Rate,Case-Fatality_Ratio
78,NaN,NaN,NaN,Azerbaijan,2020-02-28T15:03:26,NaN,NaN,1.0,0.0,0.0,NaN,NaN,02-28-2020,NaN,NaN
3015,NaN,NaN,NaN,Afghanistan,2020-05-04 02:32:28,33.93911,67.709953,2704.0,85.0,345.0,2274.0,Afghanistan,05-03-2020,NaN,NaN
3227,NaN,NaN,NaN,Afghanistan,2020-05-24 02:32:43,33.93911,67.709953,9998.0,216.0,1040.0,8742.0,Afghanistan,05-23-2020,NaN,NaN
3627,NaN,NaN,NaN,Afghanistan,2020-07-04 04:33:51,33.93911,67.709953,32324.0,819.0,17331.0,14174.0,Afghanistan,07-03-2020,83.034620,2.533721
3614,NaN,NaN,NaN,Afghanistan,2020-06-28 04:34:04,33.93911,67.709953,30616.0,703.0,10674.0,19239.0,Afghanistan,06-27-2020,78.647071,2.296185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,NaN,NaN,NaN,occupied Palestinian territory,2020-03-11T20:53:02,31.95220,35.233200,0.0,0.0,0.0,NaN,NaN,03-12-2020,NaN,NaN
79,NaN,NaN,NaN,occupied Palestinian territory,2020-03-10T19:13:21,31.95220,35.233200,25.0,0.0,0.0,NaN,NaN,03-10-2020,NaN,NaN
248,NaN,NaN,NaN,occupied Palestinian territory,2020-03-11T20:53:02,31.95220,35.233200,0.0,0.0,0.0,NaN,NaN,03-14-2020,NaN,NaN
271,NaN,NaN,NaN,occupied Palestinian territory,2020-03-11T20:53:02,31.95220,35.233200,0.0,0.0,0.0,NaN,NaN,03-16-2020,NaN,NaN
275,NaN,NaN,NaN,occupied Palestinian territory,2020-03-11T20:53:02,31.95220,35.233200,0.0,0.0,0.0,NaN,NaN,03-17-2020,NaN,NaN

In [37]:
df_daily_sorted.isna().sum()

FIPS                    65261
Admin2                  64453
Province_State          24937
Country_Region              0
Last_Update                 0
Lat                     10592
Long_                   10592
Confirmed                  19
Deaths                    441
Recovered                 388
Active                   7688
Combined_Key             7617
date                        0
Incidence_Rate         226585
Case-Fatality_Ratio    225446
dtype: int64

In [38]:
df_daily_sorted.to_csv("all_intl.csv", index=False)